version: "3"
services:
    phpmyadmin:
        image: phpmyadmin/phpmyadmin:5.0
        links:
            - db
        environment:
            PMA_HOST: db
            PMA_PORT: 3306
        ports:
            - 8081:80
    db:
        image: mysql:5.7
        ports:
            - "3306:3306"
        environment:
            - MYSQL_ROOT_PASSWORD=default
            - MYSQL_DATABASE=default
